project:
  type: website
  output-dir: docs 

website:
  title: "Guillaume Pousse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd 
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



